name: Release to NPM (manual)

on:
  # Disabled automatic publish on push. Use manual dispatch to run the job when needed.
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Increment patch version
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push --follow-tags

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
